### ISSUE TITLE
Suggestion: Style the h1 element directly, and not the div element.

### ISSUE THREAD

**Issue by josephtkim** [cantnos/prj-rev-bwfs-dasmoto#1]
Currently, the h1 text appears much larger than it should be. This is because the font-size was applied to the div element instead of the h1 element directly. To fix this, apply the styling to the h1 element directly instead, like so

```css
.header h1{
 background-image:url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
 font-size: 100px;
 font-family: helvetica;
 font-weight: bold;
 color:khaki;
 text-align: center;
}
```
