### ISSUE TITLE
Simplify: Apply shared properties in the CSS to multiple elements at once rather than individually.

### ISSUE THREAD

**Issue by josephtkim** [cantnos/prj-rev-bwfs-dasmoto#5]
It is always a good idea to simplify your code for shared properties. This will remove repetitive code and make it cleaner. The font-weight and font-family properties can be applied to multiple elements like so

```css
.header, h2, .price {
  font-family: Helvetica;
  font-weight: bold;
}
```
